module.exports = [
    {
        "name": "Men Urban Cargo Jacket",
        "description": "New season cargo jacket with modern fit.",
        "price": 4599,
        "discountPrice": null,
        "image": "new_men_cargo_jacket.png",
        "stock": 40,
        "category": "Men",
        "categoryId": "Men",
        "isAvailable": true,
        "isNewArrival": true,
        "isTrending": false,
        "isOnSale": false
    },
    {
        "name": "Men Premium Linen Shirt",
        "description": "Breathable linen shirt from latest collection.",
        "price": 2199,
        "discountPrice": null,
        "image": "new_men_linen_shirt.png",
        "stock": 60,
        "category": "Men",
        "categoryId": "Men",
        "isAvailable": true,
        "isNewArrival": true,
        "isTrending": false,
        "isOnSale": false
    },
    {
        "name": "Men Modern Fit Blazer",
        "description": "New arrival blazer for formal elegance.",
        "price": 5499,
        "discountPrice": null,
        "image": "new_men_blazer.png",
        "stock": 35,
        "category": "Men",
        "categoryId": "Men",
        "isAvailable": true,
        "isNewArrival": true,
        "isTrending": false,
        "isOnSale": false
    },
    {
        "name": "Men Graphic Street Hoodie",
        "description": "Limited edition street-style hoodie.",
        "price": 2999,
        "discountPrice": null,
        "image": "new_men_hoodie.png",
        "stock": 50,
        "category": "Men",
        "categoryId": "Men",
        "isAvailable": true,
        "isNewArrival": true,
        "isTrending": false,
        "isOnSale": false
    },
    {
        "name": "Men FlexFit Joggers",
        "description": "New sporty joggers with stretch fabric.",
        "price": 1899,
        "discountPrice": null,
        "image": "new_men_joggers.png",
        "stock": 65,
        "category": "Men",
        "categoryId": "Men",
        "isAvailable": true,
        "isNewArrival": true,
        "isTrending": false,
        "isOnSale": false
    },
    {
        "name": "Men Classic Suede Sneakers",
        "description": "Premium suede sneakers – just launched.",
        "price": 3799,
        "discountPrice": null,
        "image": "new_men_suede_sneakers.png",
        "stock": 30,
        "category": "Shoes",
        "categoryId": "Shoes",
        "isAvailable": true,
        "isNewArrival": true,
        "isTrending": false,
        "isOnSale": false
    },
    {
        "name": "Men Casual Summer Shorts",
        "description": "Lightweight summer shorts – new drop.",
        "price": 1499,
        "discountPrice": null,
        "image": "new_men_shorts.png",
        "stock": 70,
        "category": "Men",
        "categoryId": "Men",
        "isAvailable": true,
        "isNewArrival": true,
        "isTrending": false,
        "isOnSale": false
    },
    {
        "name": "Men Premium Leather Belt",
        "description": "New genuine leather belt.",
        "price": 1799,
        "discountPrice": null,
        "image": "new_men_belt.png",
        "stock": 55,
        "category": "Accessories",
        "categoryId": "Accessories",
        "isAvailable": true,
        "isNewArrival": true,
        "isTrending": false,
        "isOnSale": false
    },
    {
        "name": "Men Smart Casual Loafers",
        "description": "Elegant loafers from latest collection.",
        "price": 3499,
        "discountPrice": null,
        "image": "new_men_loafers.png",
        "stock": 35,
        "category": "Shoes",
        "categoryId": "Shoes",
        "isAvailable": true,
        "isNewArrival": true,
        "isTrending": false,
        "isOnSale": false
    },
    {
        "name": "Men Contemporary Overshirt",
        "description": "Modern overshirt for smart layering.",
        "price": 2399,
        "discountPrice": null,
        "image": "new_men_overshirt.png",
        "stock": 50,
        "category": "Men",
        "categoryId": "Men",
        "isAvailable": true,
        "isNewArrival": true,
        "isTrending": false,
        "isOnSale": false
    },
    {
        "name": "Women Satin Wrap Dress",
        "description": "New elegant satin wrap dress for evening wear.",
        "price": 3299,
        "discountPrice": null,
        "image": "new_women_satin_dress.png",
        "stock": 40,
        "category": "Women",
        "categoryId": "Women",
        "isAvailable": true,
        "isNewArrival": true,
        "isTrending": false,
        "isOnSale": false
    },
    {
        "name": "Women Chic Co-Ord Set",
        "description": "Latest matching co-ord set with modern fit.",
        "price": 3999,
        "discountPrice": null,
        "image": "new_women_coord_set.png",
        "stock": 35,
        "category": "Women",
        "categoryId": "Women",
        "isAvailable": true,
        "isNewArrival": true,
        "isTrending": false,
        "isOnSale": false
    },
    {
        "name": "Women Premium Knit Sweater",
        "description": "Soft knit sweater from the new winter drop.",
        "price": 2899,
        "discountPrice": null,
        "image": "new_women_knit_sweater.png",
        "stock": 45,
        "category": "Women",
        "categoryId": "Women",
        "isAvailable": true,
        "isNewArrival": true,
        "isTrending": false,
        "isOnSale": false
    },
    {
        "name": "Women Luxe Handbag",
        "description": "Luxury handbag from latest collection.",
        "price": 6499,
        "discountPrice": null,
        "image": "new_women_luxe_bag.png",
        "stock": 25,
        "category": "Accessories",
        "categoryId": "Accessories",
        "isAvailable": true,
        "isNewArrival": true,
        "isTrending": false,
        "isOnSale": false
    },
    {
        "name": "Women Modern Sneakers",
        "description": "Fresh drop sneakers with sleek design.",
        "price": 2999,
        "discountPrice": null,
        "image": "new_women_sneakers.png",
        "stock": 50,
        "category": "Shoes",
        "categoryId": "Shoes",
        "isAvailable": true,
        "isNewArrival": true,
        "isTrending": false,
        "isOnSale": false
    },
    {
        "name": "Women Active Gym Set",
        "description": "Latest activewear set for fitness lovers.",
        "price": 3499,
        "discountPrice": null,
        "image": "new_women_gym_set.png",
        "stock": 40,
        "category": "Women",
        "categoryId": "Women",
        "isAvailable": true,
        "isNewArrival": true,
        "isTrending": false,
        "isOnSale": false
    },
    {
        "name": "Women Statement Earrings",
        "description": "Bold statement earrings from new launch.",
        "price": 1899,
        "discountPrice": null,
        "image": "new_women_earrings.png",
        "stock": 60,
        "category": "Accessories",
        "categoryId": "Accessories",
        "isAvailable": true,
        "isNewArrival": true,
        "isTrending": false,
        "isOnSale": false
    },
    {
        "name": "Women Elegant Blazer",
        "description": "New tailored blazer for power dressing.",
        "price": 4599,
        "discountPrice": null,
        "image": "new_women_blazer.png",
        "stock": 30,
        "category": "Women",
        "categoryId": "Women",
        "isAvailable": true,
        "isNewArrival": true,
        "isTrending": false,
        "isOnSale": false
    },
    {
        "name": "Women Summer Midi Dress",
        "description": "Light summer midi dress with fresh prints.",
        "price": 2499,
        "discountPrice": null,
        "image": "new_women_midi_dress.png",
        "stock": 55,
        "category": "Women",
        "categoryId": "Women",
        "isAvailable": true,
        "isNewArrival": true,
        "isTrending": false,
        "isOnSale": false
    },
    {
        "name": "Women Leather Sandals",
        "description": "Premium leather sandals from new arrival collection.",
        "price": 2399,
        "discountPrice": null,
        "image": "new_women_sandals.png",
        "stock": 45,
        "category": "Shoes",
        "categoryId": "Shoes",
        "isAvailable": true,
        "isNewArrival": true,
        "isTrending": false,
        "isOnSale": false
    },
    {
        "name": "Men Oversized Street T-Shirt",
        "description": "Trending oversized t-shirt with bold graphics.",
        "price": 1499,
        "discountPrice": null,
        "image": "trending_men_oversized_tshirt.png",
        "stock": 70,
        "category": "Men",
        "categoryId": "Men",
        "isAvailable": true,
        "isNewArrival": false,
        "isTrending": true,
        "isOnSale": false
    },
    {
        "name": "Men Distressed Denim Jeans",
        "description": "High-demand distressed denim jeans.",
        "price": 2599,
        "discountPrice": null,
        "image": "trending_men_denim.png",
        "stock": 50,
        "category": "Men",
        "categoryId": "Men",
        "isAvailable": true,
        "isNewArrival": false,
        "isTrending": true,
        "isOnSale": false
    },
    {
        "name": "Men Classic White Sneakers",
        "description": "Most popular sneakers this season.",
        "price": 2799,
        "discountPrice": null,
        "image": "trending_men_white_sneakers.png",
        "stock": 60,
        "category": "Shoes",
        "categoryId": "Shoes",
        "isAvailable": true,
        "isNewArrival": false,
        "isTrending": true,
        "isOnSale": false
    },
    {
        "name": "Men Street Bomber Jacket",
        "description": "Trending bomber jacket with urban style.",
        "price": 3999,
        "discountPrice": null,
        "image": "trending_men_bomber.png",
        "stock": 40,
        "category": "Men",
        "categoryId": "Men",
        "isAvailable": true,
        "isNewArrival": false,
        "isTrending": true,
        "isOnSale": false
    },
    {
        "name": "Men Premium Chronograph Watch",
        "description": "Best-selling luxury chronograph watch.",
        "price": 5999,
        "discountPrice": null,
        "image": "trending_men_watch.png",
        "stock": 30,
        "category": "Accessories",
        "categoryId": "Accessories",
        "isAvailable": true,
        "isNewArrival": false,
        "isTrending": true,
        "isOnSale": false
    },
    {
        "name": "Men Slim Fit Formal Shirt",
        "description": "Most loved slim-fit formal shirt.",
        "price": 1899,
        "discountPrice": null,
        "image": "trending_men_formal_shirt.png",
        "stock": 65,
        "category": "Men",
        "categoryId": "Men",
        "isAvailable": true,
        "isNewArrival": false,
        "isTrending": true,
        "isOnSale": false
    },
    {
        "name": "Men Casual Loafers",
        "description": "Trending loafers with modern finish.",
        "price": 3299,
        "discountPrice": null,
        "image": "trending_men_loafers.png",
        "stock": 35,
        "category": "Shoes",
        "categoryId": "Shoes",
        "isAvailable": true,
        "isNewArrival": false,
        "isTrending": true,
        "isOnSale": false
    },
    {
        "name": "Men Active Joggers",
        "description": "Trending athletic joggers with comfort fit.",
        "price": 1799,
        "discountPrice": null,
        "image": "trending_men_joggers.png",
        "stock": 60,
        "category": "Men",
        "categoryId": "Men",
        "isAvailable": true,
        "isNewArrival": false,
        "isTrending": true,
        "isOnSale": false
    },
    {
        "name": "Men Graphic Hoodie",
        "description": "Streetwear hoodie trending this season.",
        "price": 2999,
        "discountPrice": null,
        "image": "trending_men_hoodie.png",
        "stock": 50,
        "category": "Men",
        "categoryId": "Men",
        "isAvailable": true,
        "isNewArrival": false,
        "isTrending": true,
        "isOnSale": false
    },
    {
        "name": "Men Casual Backpack",
        "description": "High-demand everyday backpack.",
        "price": 2799,
        "discountPrice": null,
        "image": "trending_men_backpack.png",
        "stock": 45,
        "category": "Accessories",
        "categoryId": "Accessories",
        "isAvailable": true,
        "isNewArrival": false,
        "isTrending": true,
        "isOnSale": false
    },
    {
        "name": "Women Oversized Blazer",
        "description": "Trending oversized blazer for modern fashion.",
        "price": 4599,
        "discountPrice": null,
        "image": "trending_women_blazer.png",
        "stock": 35,
        "category": "Women",
        "categoryId": "Women",
        "isAvailable": true,
        "isNewArrival": false,
        "isTrending": true,
        "isOnSale": false
    },
    {
        "name": "Women Wide Leg Trousers",
        "description": "High-demand wide leg trousers with elegant fit.",
        "price": 2599,
        "discountPrice": null,
        "image": "trending_women_trousers.png",
        "stock": 50,
        "category": "Women",
        "categoryId": "Women",
        "isAvailable": true,
        "isNewArrival": false,
        "isTrending": true,
        "isOnSale": false
    },
    {
        "name": "Women Chunky Sneakers",
        "description": "Most popular chunky sneakers this season.",
        "price": 2999,
        "discountPrice": null,
        "image": "trending_women_chunky_sneakers.png",
        "stock": 45,
        "category": "Shoes",
        "categoryId": "Shoes",
        "isAvailable": true,
        "isNewArrival": false,
        "isTrending": true,
        "isOnSale": false
    },
    {
        "name": "Women Elegant Satin Dress",
        "description": "Trending satin dress for evening wear.",
        "price": 3499,
        "discountPrice": null,
        "image": "trending_women_satin_dress.png",
        "stock": 40,
        "category": "Women",
        "categoryId": "Women",
        "isAvailable": true,
        "isNewArrival": false,
        "isTrending": true,
        "isOnSale": false
    },
    {
        "name": "Women Statement Handbag",
        "description": "High-demand statement handbag.",
        "price": 5999,
        "discountPrice": null,
        "image": "trending_women_handbag.png",
        "stock": 30,
        "category": "Accessories",
        "categoryId": "Accessories",
        "isAvailable": true,
        "isNewArrival": false,
        "isTrending": true,
        "isOnSale": false
    },
    {
        "name": "Women Active Leggings",
        "description": "Trending gym leggings with stretch comfort.",
        "price": 1599,
        "discountPrice": null,
        "image": "trending_women_leggings.png",
        "stock": 60,
        "category": "Women",
        "categoryId": "Women",
        "isAvailable": true,
        "isNewArrival": false,
        "isTrending": true,
        "isOnSale": false
    },
    {
        "name": "Women Classic Heels",
        "description": "Trending classic heels for formal look.",
        "price": 2999,
        "discountPrice": null,
        "image": "trending_women_heels.png",
        "stock": 40,
        "category": "Shoes",
        "categoryId": "Shoes",
        "isAvailable": true,
        "isNewArrival": false,
        "isTrending": true,
        "isOnSale": false
    },
    {
        "name": "Women Designer Sunglasses",
        "description": "Most loved sunglasses this season.",
        "price": 3299,
        "discountPrice": null,
        "image": "trending_women_sunglasses.png",
        "stock": 45,
        "category": "Accessories",
        "categoryId": "Accessories",
        "isAvailable": true,
        "isNewArrival": false,
        "isTrending": true,
        "isOnSale": false
    },
    {
        "name": "Women Ribbed Knit Top",
        "description": "Trending ribbed knit top for casual style.",
        "price": 1399,
        "discountPrice": null,
        "image": "trending_women_knit_top.png",
        "stock": 65,
        "category": "Women",
        "categoryId": "Women",
        "isAvailable": true,
        "isNewArrival": false,
        "isTrending": true,
        "isOnSale": false
    },
    {
        "name": "Women Minimal Gold Necklace",
        "description": "Trending minimalist gold necklace.",
        "price": 1999,
        "discountPrice": null,
        "image": "trending_women_necklace.png",
        "stock": 55,
        "category": "Accessories",
        "categoryId": "Accessories",
        "isAvailable": true,
        "isNewArrival": false,
        "isTrending": true,
        "isOnSale": false
    },
    {
        "name": "Men Casual Check Shirt",
        "description": "Discounted casual check shirt.",
        "price": 1999,
        "discountPrice": 1499,
        "image": "sale_men_check_shirt.png",
        "stock": 60,
        "category": "Men",
        "categoryId": "Men",
        "isAvailable": true,
        "isNewArrival": false,
        "isTrending": false,
        "isOnSale": true
    },
    {
        "name": "Men Slim Fit Jeans",
        "description": "Best-selling jeans now on sale.",
        "price": 2599,
        "discountPrice": 1999,
        "image": "sale_men_jeans.png",
        "stock": 50,
        "category": "Men",
        "categoryId": "Men",
        "isAvailable": true,
        "isNewArrival": false,
        "isTrending": false,
        "isOnSale": true
    },
    {
        "name": "Men Sport Sneakers",
        "description": "Limited-time discount on sport sneakers.",
        "price": 3299,
        "discountPrice": 2599,
        "image": "sale_men_sneakers.png",
        "stock": 45,
        "category": "Shoes",
        "categoryId": "Shoes",
        "isAvailable": true,
        "isNewArrival": false,
        "isTrending": false,
        "isOnSale": true
    },
    {
        "name": "Men Hoodie Jacket",
        "description": "Winter hoodie jacket on special offer.",
        "price": 2999,
        "discountPrice": 2299,
        "image": "sale_men_hoodie.png",
        "stock": 40,
        "category": "Men",
        "categoryId": "Men",
        "isAvailable": true,
        "isNewArrival": false,
        "isTrending": false,
        "isOnSale": true
    },
    {
        "name": "Men Leather Wallet",
        "description": "Premium leather wallet at discounted price.",
        "price": 1799,
        "discountPrice": 1299,
        "image": "sale_men_wallet.png",
        "stock": 70,
        "category": "Accessories",
        "categoryId": "Accessories",
        "isAvailable": true,
        "isNewArrival": false,
        "isTrending": false,
        "isOnSale": true
    },
    {
        "name": "Men Running Shoes",
        "description": "Performance running shoes now on sale.",
        "price": 3499,
        "discountPrice": 2799,
        "image": "sale_men_running.png",
        "stock": 35,
        "category": "Shoes",
        "categoryId": "Shoes",
        "isAvailable": true,
        "isNewArrival": false,
        "isTrending": false,
        "isOnSale": true
    },
    {
        "name": "Men Formal Blazer",
        "description": "Premium blazer at limited-time discount.",
        "price": 5499,
        "discountPrice": 4299,
        "image": "sale_men_blazer.png",
        "stock": 30,
        "category": "Men",
        "categoryId": "Men",
        "isAvailable": true,
        "isNewArrival": false,
        "isTrending": false,
        "isOnSale": true
    },
    {
        "name": "Men Casual Loafers 2",
        "description": "Comfort loafers available at special price.",
        "price": 3299,
        "discountPrice": 2499,
        "image": "sale_men_loafers.png",
        "stock": 40,
        "category": "Shoes",
        "categoryId": "Shoes",
        "isAvailable": true,
        "isNewArrival": false,
        "isTrending": false,
        "isOnSale": true
    },
    {
        "name": "Men Polo T-Shirt",
        "description": "Classic polo tee on seasonal sale.",
        "price": 1499,
        "discountPrice": 1099,
        "image": "sale_men_polo.png",
        "stock": 65,
        "category": "Men",
        "categoryId": "Men",
        "isAvailable": true,
        "isNewArrival": false,
        "isTrending": false,
        "isOnSale": true
    },
    {
        "name": "Men Travel Backpack",
        "description": "Durable backpack now at reduced price.",
        "price": 2999,
        "discountPrice": 2299,
        "image": "sale_men_backpack.png",
        "stock": 45,
        "category": "Accessories",
        "categoryId": "Accessories",
        "isAvailable": true,
        "isNewArrival": false,
        "isTrending": false,
        "isOnSale": true
    },
    {
        "name": "Women Floral Midi Dress",
        "description": "Beautiful floral midi dress now available at discounted price.",
        "price": 2499,
        "discountPrice": 1899,
        "image": "sale_women_floral_dress.png",
        "stock": 50,
        "category": "Women",
        "categoryId": "Women",
        "isAvailable": true,
        "isNewArrival": false,
        "isTrending": false,
        "isOnSale": true
    },
    {
        "name": "Women High-Waist Jeans",
        "description": "Premium high-waist jeans on special offer.",
        "price": 2799,
        "discountPrice": 2199,
        "image": "sale_women_jeans.png",
        "stock": 45,
        "category": "Women",
        "categoryId": "Women",
        "isAvailable": true,
        "isNewArrival": false,
        "isTrending": false,
        "isOnSale": true
    },
    {
        "name": "Women Classic Heels 2",
        "description": "Elegant heels now available at reduced price.",
        "price": 2999,
        "discountPrice": 2399,
        "image": "sale_women_heels.png",
        "stock": 40,
        "category": "Shoes",
        "categoryId": "Shoes",
        "isAvailable": true,
        "isNewArrival": false,
        "isTrending": false,
        "isOnSale": true
    },
    {
        "name": "Women Leather Handbag",
        "description": "Premium leather handbag on limited-time discount.",
        "price": 6499,
        "discountPrice": 4999,
        "image": "sale_women_handbag.png",
        "stock": 30,
        "category": "Accessories",
        "categoryId": "Accessories",
        "isAvailable": true,
        "isNewArrival": false,
        "isTrending": false,
        "isOnSale": true
    },
    {
        "name": "Women Sports Leggings",
        "description": "Comfortable leggings now on seasonal sale.",
        "price": 1599,
        "discountPrice": 1199,
        "image": "sale_women_leggings.png",
        "stock": 60,
        "category": "Women",
        "categoryId": "Women",
        "isAvailable": true,
        "isNewArrival": false,
        "isTrending": false,
        "isOnSale": true
    },
    {
        "name": "Women Designer Sunglasses 2",
        "description": "Luxury sunglasses available at discounted rate.",
        "price": 3299,
        "discountPrice": 2599,
        "image": "sale_women_sunglasses.png",
        "stock": 35,
        "category": "Accessories",
        "categoryId": "Accessories",
        "isAvailable": true,
        "isNewArrival": false,
        "isTrending": false,
        "isOnSale": true
    },
    {
        "name": "Women Casual Sneakers",
        "description": "Trendy sneakers now at special offer.",
        "price": 2899,
        "discountPrice": 2199,
        "image": "sale_women_sneakers.png",
        "stock": 50,
        "category": "Shoes",
        "categoryId": "Shoes",
        "isAvailable": true,
        "isNewArrival": false,
        "isTrending": false,
        "isOnSale": true
    },
    {
        "name": "Women Elegant Blazer 2",
        "description": "Formal blazer now available at reduced price.",
        "price": 4599,
        "discountPrice": 3599,
        "image": "sale_women_blazer.png",
        "stock": 35,
        "category": "Women",
        "categoryId": "Women",
        "isAvailable": true,
        "isNewArrival": false,
        "isTrending": false,
        "isOnSale": true
    },
    {
        "name": "Women Statement Earrings 2",
        "description": "Beautiful earrings now on special sale.",
        "price": 1899,
        "discountPrice": 1399,
        "image": "sale_women_earrings.png",
        "stock": 65,
        "category": "Accessories",
        "categoryId": "Accessories",
        "isAvailable": true,
        "isNewArrival": false,
        "isTrending": false,
        "isOnSale": true
    },
    {
        "name": "Women Summer Sandals",
        "description": "Comfort summer sandals at discounted price.",
        "price": 1999,
        "discountPrice": 1499,
        "image": "sale_women_sandals.png",
        "stock": 55,
        "category": "Shoes",
        "categoryId": "Shoes",
        "isAvailable": true,
        "isNewArrival": false,
        "isTrending": false,
        "isOnSale": true
    }
];
